mysql:
  image: mysql
  restart: always
  ports:
    - 3306:3306
  environment:
    - MYSQL_USER=testuser
    - MYSQL_PASSWORD=testpass
    - MYSQL_DATABASE=car_seller
    - MYSQL_ROOT_PASSWORD=pass
  volumes:
    - ./conf.d:/etc/mysql/conf.d:ro